from discipline import Discipline

"""
Based on https://de.wikipedia.org/wiki/Einzelwissenschaft
"""
course_disciple_map = {
    "Agrarwissenschaften": Discipline.Agrarwissenschaften,
    "Architektur": Discipline.Ingenieurwissenschaften,
    "Automotive Systems": Discipline.Ingenieurwissenschaften,
    "BWL": Discipline.Wirtschaftswissenschaften,
    "Bau- u. Verkehrswesen": Discipline.Ingenieurwissenschaften,
    "Bauingenieurwesen": Discipline.Ingenieurwissenschaften,
    "Bauwesen": Discipline.Ingenieurwissenschaften,
    "Bekleidungsgestaltung": Discipline.Geisteswissenschaften,
    "Bergbau": Discipline.Ingenieurwissenschaften,
    "Bioinformatik": Discipline.Naturwissenschaften,
    "Biologie": Discipline.Naturwissenschaften,
    "Biotechnologie": Discipline.Ingenieurwissenschaften,
    "CIW / Verfahrenstechnik": Discipline.Ingenieurwissenschaften,
    "Chemie": Discipline.Naturwissenschaften,
    "Chemie,  Physik": Discipline.Naturwissenschaften,
    "Chemieingenieurwesen": Discipline.Ingenieurwissenschaften,
    "Computational Engineering": Discipline.Strukturwissenschaften,
    "Eisenbahntechnik": Discipline.Ingenieurwissenschaften,
    "Elektro-und Energietechnik": Discipline.Ingenieurwissenschaften,
    "Elektrotechnik": Discipline.Ingenieurwissenschaften,
    "Energie- u. Verfahrenstechnik": Discipline.Ingenieurwissenschaften,
    "Erneubare Energien": Discipline.Ingenieurwissenschaften,
    "Fahrzeugtechnologie": Discipline.Ingenieurwissenschaften,
    "Flugtechnik": Discipline.Ingenieurwissenschaften,
    "Geophysik": Discipline.Naturwissenschaften,
    "Germanistik / Geographie": Discipline.Geisteswissenschaften,
    "Hochfrequenztechnik & Opt. NT": Discipline.Ingenieurwissenschaften,
    "Hüttenwesen": Discipline.Ingenieurwissenschaften,
    "Industrial Design": Discipline.Geisteswissenschaften,
    "Informatik": Discipline.Strukturwissenschaften,
    "Informationswirtschaft": Discipline.Wirtschaftswissenschaften,
    "International Management": Discipline.Geisteswissenschaften,
    "Jura": Discipline.Rechtswissenschaften,
    "Konstruktion": Discipline.Ingenieurwissenschaften,
    "Kulturtechnik": Discipline.Ingenieurwissenschaften,
    "Kunst": Discipline.Geisteswissenschaften,
    "Kunstgeschichte": Discipline.Geisteswissenschaften,
    "Landschaftsarchitektur/-planung": Discipline.Ingenieurwissenschaften,
    "Lebensmittelchemie": Discipline.Naturwissenschaften,
    "Lebensmitteltechnologie": Discipline.Ingenieurwissenschaften,
    "Lehramt": Discipline.Geisteswissenschaften,
    "Maschinenbau": Discipline.Ingenieurwissenschaften,
    "Maschinenbau / Jura": Discipline.Ingenieurwissenschaften,
    "Maschinenbau / Wi-In": Discipline.Ingenieurwissenschaften,
    "Mathematik": Discipline.Strukturwissenschaften,
    "Mathematik,  Sport": Discipline.Naturwissenschaften,
    "Mechatronik": Discipline.Ingenieurwissenschaften,
    "Medieninformatik": Discipline.Strukturwissenschaften,
    "Medienmanagement": Discipline.Geisteswissenschaften,
    "Medientechnik": Discipline.Ingenieurwissenschaften,
    "Medizin": Discipline.Naturwissenschaften.Naturwissenschaften,
    "Messe-,  Kongress-,  Eventmanagement": Discipline.Geisteswissenschaften,
    "Nachrichtentechnik": Discipline.Ingenieurwissenschaften,
    "Pharmazie": Discipline.Naturwissenschaften,
    "Philosophie und Technikgeschichte": Discipline.Geisteswissenschaften,
    "Physik": Discipline.Naturwissenschaften,
    "Physik,  TWLAK": Discipline.Naturwissenschaften,
    "Physikal. Ingenieurwissenschaft": Discipline.Ingenieurwissenschaften,
    "Politologie": Discipline.Sozialwissenschaften,
    "Product Engineering": Discipline.Geisteswissenschaften,
    "Psychologie": Discipline.Sozialwissenschaften,
    "Puppenspiel": Discipline.Geisteswissenschaften,
    "Pädagogik": Discipline.Geisteswissenschaften,
    "Rechtswissenschaften": Discipline.Rechtswissenschaften,
    "Sensorik": Discipline.Ingenieurwissenschaften,
    "Soziale Arbeit": Discipline.Sozialwissenschaften,
    "Sozialwesen / Relegionspädagogik": Discipline.Sozialwissenschaften,
    "Soziologie": Discipline.Sozialwissenschaften,
    "Stadtplanung/ Landschaftsarchitektur": Discipline.Ingenieurwissenschaften,
    "TWLAK Lebensmittelchemie": Discipline.Naturwissenschaften,
    "Technische Informatik": Discipline.Ingenieurwissenschaften,
    "Technomathematik": Discipline.Strukturwissenschaften,
    "Theoretische Physik": Discipline.Naturwissenschaften,
    "Tourismusmanagement": Discipline.Sozialwissenschaften,
    "Verfahrenstechnik": Discipline.Ingenieurwissenschaften,
    "Verkehrswesen": Discipline.Ingenieurwissenschaften,
    "Verkehrswesen (Flugtechnik)": Discipline.Ingenieurwissenschaften,
    "Verwaltungswirtschaft": Discipline.Wirtschaftswissenschaften,
    "Volkswirtschaftslehre": Discipline.Wirtschaftswissenschaften,
    "Werkstoffwissenschaften": Discipline.Ingenieurwissenschaften,
    "Wi.-Ing. (Elektrotechnik)": Discipline.Ingenieurwissenschaften,
    "Wi.-Ing. (Maschinenau)": Discipline.Ingenieurwissenschaften,
    "Wi.-Ing. OR + Informatik": Discipline.Ingenieurwissenschaften,
    "Wi.-Ing. Operation Research": Discipline.Wirtschaftswissenschaften,
    "Wi.-Ing.,  Sozialpädagogik": Discipline.Ingenieurwissenschaften,
    "Wi.-So.": Discipline.Wirtschaftswissenschaften,
    "Wirtschafts-Mathematik": Discipline.Wirtschaftswissenschaften,
    "Wirtschaftsinformatik": Discipline.Wirtschaftswissenschaften,
    "Wirtschaftsingenieurwesen": Discipline.Wirtschaftswissenschaften,
    "Wirtschaftswissenschaft": Discipline.Wirtschaftswissenschaften,
    "Wiwi. Versicherung": Discipline.Wirtschaftswissenschaften
}


def get_map():
    return course_disciple_map


class Test(object):
    pass
